# Generated by Django 5.2.6 on 2025-10-12 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام پلن')),
                ('plan_type', models.CharField(choices=[('basic', 'پایه'), ('standard', 'نقره\u200cای'), ('premium', 'طلایی'), ('advanced', 'الماسی')], max_length=20, verbose_name='نوع پلن')),
                ('duration_type', models.CharField(choices=[('one_month', 'یک ماهه'), ('three_months', 'سه ماهه'), ('six_months', 'شش ماهه'), ('one_year', 'یک ساله')], max_length=20, verbose_name='نوع مدت')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='قیمت')),
                ('duration_days', models.IntegerField(verbose_name='مدت به روز')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'پلن اشتراک',
                'verbose_name_plural': 'پلن\u200c های اشتراک',
            },
        ),
    ]
