# Generated by Django 5.2.6 on 2025-10-12 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='price',
            field=models.PositiveIntegerField(verbose_name='قیمت'),
        ),
    ]
