# Generated by Django 5.2.6 on 2025-10-13 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0004_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionplan',
            name='plan_type',
        ),
    ]
