# Generated by Django 5.2.6 on 2025-10-15 02:54

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='عنوان مقاله')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='اسلاگ')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='توضیحات')),
                ('list_banner', models.ImageField(blank=True, help_text='برای نمایش بهتر، تصویر را با ابعاد 900x600 پیکسل بارگذاری کنید', null=True, upload_to='articles/list_banner/', verbose_name='بنر لیست مقاله')),
                ('detail_banner', models.ImageField(blank=True, help_text='برای نمایش بهتر، تصویر را با ابعاد 1000x600 پیکسل بارگذاری کنید', null=True, upload_to='articles/detail_banner/', verbose_name='بنر جزئیات مقاله')),
                ('status', models.CharField(choices=[('draft', 'پیش نویس شود'), ('published', 'منتشر شود')], default='published', max_length=10, verbose_name='وضعیت')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='بازدید ها')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('category', models.ManyToManyField(related_name='articles', to='blog.category', verbose_name='دسته بندی')),
                ('tag', models.ManyToManyField(related_name='articles', to='blog.tag', verbose_name='برچسب')),
            ],
            options={
                'verbose_name': 'مقاله',
                'verbose_name_plural': 'مقالات',
            },
        ),
    ]
