# Generated by Django 5.2.6 on 2025-09-19 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='عنوان ژانر')),
                ('slug', models.SlugField(unique=True, verbose_name='نامک')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='genre_thumbnails/', verbose_name='تصویر ژانر')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'ژانر',
                'verbose_name_plural': 'ژانر ها',
            },
        ),
    ]
