# Generated by Django 5.2.6 on 2025-09-19 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='نام کشور')),
                ('slug', models.SlugField(unique=True, verbose_name='نامک')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'کشور',
                'verbose_name_plural': 'کشور ها',
            },
        ),
    ]
