# Generated by Django 5.2.6 on 2025-09-19 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='اسم کارگردان')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='نامک')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='بیوگرافی')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='directors_photos/', verbose_name='عکس کارگردان')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'کارگردان',
                'verbose_name_plural': 'کارگردانان',
            },
        ),
    ]
