# Generated by Django 5.2.6 on 2025-09-19 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0006_director'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='اسم بازیگر')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='نامک')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='بیوگرافی')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='actors_photos/', verbose_name='عکس بازیگر')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'بازیگر',
                'verbose_name_plural': 'بازیگران',
            },
        ),
    ]
