# Generated by Django 5.2.6 on 2025-09-19 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0007_actor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='عنوان فیلم')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='نامک')),
                ('description', models.TextField(verbose_name='خلاصه داستان')),
                ('vertical_banner', models.ImageField(blank=True, help_text='برای نمایش بهتر، تصویر را با ابعاد 800x1050 پیکسل بارگذاری کنید', null=True, upload_to='movies/movie_vertical_banner/', verbose_name='بنر عمودی فیلم')),
                ('horizontal_banner', models.ImageField(blank=True, help_text='برای نمایش بهتر، تصویر را با ابعاد 3320x1280 پیکسل بارگذاری کنید', null=True, upload_to='movies/movie_horizontal_banner/', verbose_name='بنر افقی فیلم')),
                ('duration', models.CharField(max_length=5, verbose_name='مدت زمان فیلم (لطفا مدت زمان را به دقیقه وارد کنید)')),
                ('score', models.CharField(default='0.0/10', max_length=10, verbose_name='امتیاز')),
                ('age_range', models.CharField(default='بالای 14 سال', max_length=20, verbose_name='رنج سنی')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='بازدید ها')),
                ('trailer', models.URLField(max_length=500, verbose_name='لینک تریلر فیلم')),
                ('subtitle_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='لینک زیرنویس فیلم')),
                ('quality_480p', models.URLField(blank=True, max_length=500, null=True, verbose_name='لینک کیفیت 480p')),
                ('quality_720p', models.URLField(blank=True, max_length=500, null=True, verbose_name='لینک کیفیت 720p')),
                ('quality_1080p', models.URLField(blank=True, max_length=500, null=True, verbose_name='لینک کیفیت 1080p')),
                ('dubbed_or_subtitle', models.CharField(choices=[('dubbed', 'دوبله فارسی'), ('subtitled', 'زیرنویس فارسی')], default='dubbed', max_length=10, verbose_name='وضعیت دوبله یا زیرنویس')),
                ('subscription_status', models.CharField(choices=[('free', 'رایگان'), ('subscription', 'اشتراکی')], default='subscription', max_length=12, verbose_name='وضعیت اشتراکی')),
                ('is_recommended', models.BooleanField(default=False, verbose_name='آیا فیلم، پیشنهادی است؟')),
                ('status', models.CharField(choices=[('draft', 'پیش نویس شود'), ('published', 'منتشر شود')], default='published', max_length=10, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('actors', models.ManyToManyField(related_name='movies_actor', to='movie.actor', verbose_name='بازیگران')),
                ('country', models.ManyToManyField(related_name='movie_country', to='movie.country', verbose_name='کشور سازنده')),
                ('director', models.ManyToManyField(related_name='movies_director', to='movie.director', verbose_name='کارگردانان')),
                ('genre', models.ManyToManyField(related_name='movies_genre', to='movie.genre', verbose_name='ژانر')),
                ('language', models.ManyToManyField(related_name='movies_language', to='movie.language', verbose_name='زبان فیلم')),
                ('release_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_year', to='movie.year', verbose_name='تاریخ انتشار')),
                ('similar_movies', models.ManyToManyField(blank=True, null=True, related_name='similar', to='movie.movie', verbose_name='فیلم های مشابه')),
                ('tags', models.ManyToManyField(blank=True, null=True, related_name='movies_tag', to='movie.tag', verbose_name='برچسب')),
            ],
            options={
                'verbose_name': 'فیلم',
                'verbose_name_plural': 'فیلم ها',
                'indexes': [models.Index(fields=['title'], name='movie_movie_title_0a2a49_idx')],
            },
        ),
    ]
