# Generated by Django 5.2.6 on 2025-09-19 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0008_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='tags',
            field=models.ManyToManyField(related_name='movies_tag', to='movie.tag', verbose_name='برچسب'),
        ),
    ]
