# Generated by Django 5.2.6 on 2025-09-19 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0009_alter_movie_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='عنوان سریال')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='نامک')),
                ('description', models.TextField(verbose_name='خلاصه داستان')),
                ('vertical_banner', models.ImageField(blank=True, help_text='برای نمایش بهتر، تصویر را با ابعاد 800x1050 پیکسل بارگذاری کنید', null=True, upload_to='series/series_vertical_banner/', verbose_name='بنر عمودی سریال')),
                ('horizontal_banner', models.ImageField(blank=True, help_text='برای نمایش بهتر، تصویر را با ابعاد 3320x1280 پیکسل بارگذاری کنید', null=True, upload_to='series/series_horizontal_banner/', verbose_name='بنر افقی سریال')),
                ('duration', models.CharField(max_length=5, verbose_name='مدت زمان سریال (لطفا مدت زمان را به دقیقه وارد کنید)')),
                ('chapter_count', models.PositiveIntegerField(verbose_name='تعداد فصل ها')),
                ('score', models.CharField(default='0.0/10', max_length=10, verbose_name='امتیاز')),
                ('age_range', models.CharField(default='بالای 14 سال', max_length=20, verbose_name='رنج سنی')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='بازدید ها')),
                ('trailer', models.URLField(max_length=500, verbose_name='لینک تریلر سریال')),
                ('subtitle_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='لینک زیرنویس سریال')),
                ('dubbed_or_subtitle', models.CharField(choices=[('dubbed', 'دوبله فارسی'), ('subtitled', 'زیرنویس فارسی')], default='dubbed', max_length=10, verbose_name='وضعیت دوبله یا زیرنویس')),
                ('subscription_status', models.CharField(choices=[('free', 'رایگان'), ('subscription', 'اشتراکی')], default='subscription', max_length=12, verbose_name='وضعیت اشتراکی')),
                ('is_recommended', models.BooleanField(default=False, verbose_name='آیا سریال، پیشنهادی است؟')),
                ('status', models.CharField(choices=[('draft', 'پیش نویس شود'), ('published', 'منتشر شود')], default='published', max_length=10, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('actors', models.ManyToManyField(related_name='series_actor', to='movie.actor', verbose_name='بازیگران')),
                ('country', models.ManyToManyField(related_name='series_country', to='movie.country', verbose_name='کشور سازنده')),
                ('director', models.ManyToManyField(related_name='series_director', to='movie.director', verbose_name='کارگردانان')),
                ('genre', models.ManyToManyField(related_name='series_genre', to='movie.genre', verbose_name='ژانر')),
                ('language', models.ManyToManyField(related_name='series_language', to='movie.language', verbose_name='زبان سریال')),
                ('release_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series_year', to='movie.year', verbose_name='تاریخ انتشار')),
                ('similar_series', models.ManyToManyField(blank=True, null=True, related_name='similar', to='movie.series', verbose_name='سریال های مشابه')),
                ('tags', models.ManyToManyField(related_name='series_tag', to='movie.tag', verbose_name='برچسب')),
            ],
            options={
                'verbose_name': 'سریال',
                'verbose_name_plural': 'سریال ها',
                'indexes': [models.Index(fields=['title'], name='movie_serie_title_5fcc77_idx')],
            },
        ),
    ]
