# Generated by Django 5.2.6 on 2025-09-19 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0010_series'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChapterSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان فصل')),
                ('order', models.PositiveIntegerField(verbose_name='ترتیب فصل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.series', verbose_name='سریال مربوطه')),
            ],
            options={
                'verbose_name': 'فصل سریال',
                'verbose_name_plural': 'فصل های سریال',
            },
        ),
    ]
