# Generated by Django 5.2.6 on 2025-09-19 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0011_chapterseries'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality_480p', models.URLField(blank=True, max_length=500, null=True, verbose_name='لینک کیفیت 480p')),
                ('quality_720p', models.URLField(blank=True, max_length=500, null=True, verbose_name='لینک کیفیت 720p')),
                ('quality_1080p', models.URLField(blank=True, max_length=500, null=True, verbose_name='لینک کیفیت 1080p')),
                ('subtitle', models.URLField(blank=True, max_length=500, null=True, verbose_name='لینک زیرنویس قسمت')),
                ('order', models.PositiveIntegerField(verbose_name='ترتیب ویدیو')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.chapterseries', verbose_name='فصل مربوطه')),
            ],
            options={
                'verbose_name': 'قسمت سریال',
                'verbose_name_plural': 'قسمت های سریال',
            },
        ),
    ]
