# Generated by Django 5.2.6 on 2025-09-19 06:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0013_moviecomment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SeriesComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='متن دیدگاه')),
                ('status', models.CharField(choices=[('draft', 'پیش نویس شود'), ('published', 'منتشر شود')], default='published', max_length=10, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series_comments', to=settings.AUTH_USER_MODEL, verbose_name='نویسنده دیدگاه')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series_comments', to='movie.series', verbose_name='سریال مربوطه')),
            ],
            options={
                'verbose_name': 'دیدگاه سریال',
                'verbose_name_plural': 'دیدگاه های سریال ها',
            },
        ),
    ]
