# Generated by Django 5.2.6 on 2025-09-23 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0014_seriescomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='chapter_count',
            field=models.PositiveIntegerField(help_text='این فیلد به صورت خودکار پس از افزودن یا حذف فصل به\u200cروزرسانی می\u200cشود', verbose_name='تعداد فصل ها'),
        ),
    ]
