# Generated by Django 5.2.6 on 2025-09-27 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0016_director_awards_director_date_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='awards',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='تعداد جوایز'),
        ),
        migrations.AddField(
            model_name='actor',
            name='date_birth',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ تولد'),
        ),
        migrations.AddField(
            model_name='actor',
            name='education',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='تحصیلات'),
        ),
        migrations.AddField(
            model_name='actor',
            name='facebook_url',
            field=models.URLField(blank=True, null=True, verbose_name='آدرس فیسبوک'),
        ),
        migrations.AddField(
            model_name='actor',
            name='instagram_url',
            field=models.URLField(blank=True, null=True, verbose_name='آدرس اینستاگرام'),
        ),
        migrations.AddField(
            model_name='actor',
            name='place_birth',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='محل تولد'),
        ),
        migrations.AddField(
            model_name='actor',
            name='twitter_url',
            field=models.URLField(blank=True, null=True, verbose_name='آدرس توییتر'),
        ),
    ]
